# Generated by Django 3.0.4 on 2020-03-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='top20warning',
            field=models.BooleanField(default=False),
        ),
    ]
